import DarkModeToggle from "./components/DarkModeToggle/DarkModeToggle";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Where in the world",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="h-20 flex items-center px-24 bg-white mb-16 justify-between drop-shadow">
          <h1 className="text-3xl">Where in the world?</h1>
          <DarkModeToggle />
        </nav>
        <div className="container mx-auto px-4 mb-16">{children}</div>
      </body>
    </html>
  );
}
