export const data = [
  {
    name: {
      common: "Colombia",
      official: "Republic of Colombia",
      nativeName: {
        spa: { official: "República de Colombia", common: "Colombia" },
      },
    },
    tld: [".co"],
    cca2: "CO",
    ccn3: "170",
    cca3: "COL",
    cioc: "COL",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { COP: { name: "Colombian peso", symbol: "$" } },
    idd: { root: "+5", suffixes: ["7"] },
    capital: "Bogotá",
    altSpellings: ["CO", "Republic of Colombia", "República de Colombia"],
    region: "Americas",
    subregion: "South America",
    languages: { spa: "Spanish" },
    translations: {
      ara: { official: "جمهورية كولومبيا", common: "كولومبيا" },
      bre: { official: "Republik Kolombia", common: "Kolombia" },
      ces: { official: "Kolumbijská republika", common: "Kolumbie" },
      cym: { official: "Gweriniaeth Colombia", common: "Colombia" },
      deu: { official: "Republik Kolumbien", common: "Kolumbien" },
      est: { official: "Colombia Vabariik", common: "Colombia" },
      fin: { official: "Kolumbian tasavalta", common: "Kolumbia" },
      fra: { official: "République de Colombie", common: "Colombie" },
      hrv: { official: "Republika Kolumbija", common: "Kolumbija" },
      hun: { official: "Kolumbiai Köztársaság", common: "Kolumbia" },
      ita: { official: "Repubblica di Colombia", common: "Colombia" },
      jpn: { official: "コロンビア共和国", common: "コロンビア" },
      kor: { official: "콜롬비아 공화국", common: "콜롬비아" },
      nld: { official: "Republiek Colombia", common: "Colombia" },
      per: { official: "جمهوری کلمبیا", common: "کلمبیا" },
      pol: { official: "Republika Kolumbii", common: "Kolumbia" },
      por: { official: "República da Colômbia", common: "Colômbia" },
      rus: { official: "Республика Колумбия", common: "Колумбия" },
      slk: { official: "Kolumbijská republika", common: "Kolumbia" },
      spa: { official: "República de Colombia", common: "Colombia" },
      srp: { official: "Република Колумбија", common: "Колумбија" },
      swe: { official: "Republiken Colombia", common: "Colombia" },
      tur: { official: "Kolombiya Cumhuriyeti", common: "Kolombiya" },
      urd: { official: "جمہوریہ کولمبیا", common: "کولمبیا" },
      zho: { official: "哥伦比亚共和国", common: "哥伦比亚" },
    },
    latlng: [4.0, -72.0],
    landlocked: false,
    borders: ["BRA", "ECU", "PAN", "PER", "VEN"],
    area: 1141748.0,
    demonyms: {
      eng: { f: "Colombian", m: "Colombian" },
      fra: { f: "Colombienne", m: "Colombien" },
    },
    flag: "\uD83C\uDDE8\uD83C\uDDF4",
    maps: {
      googleMaps: "https://goo.gl/maps/RdwTG8e7gPwS62oR6",
      openStreetMaps: "https://www.openstreetmap.org/relation/120027",
    },
    population: 1234,
    gini: { 2019: 51.3 },
    fifa: "COL",
    car: { signs: ["CO"], side: "right" },
    timezones: ["UTC-05:00"],
    continents: ["South America"],
    flags: {
      png: "https://flagcdn.com/w320/co.png",
      svg: "https://flagcdn.com/co.svg",
      alt: "The flag of Colombia.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/co.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/co.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [4.71, -74.07] },
  },
  {
    name: {
      common: "Argentina",
      official: "Argentine Republic",
      nativeName: {
        grn: { official: "Argentine Republic", common: "Argentina" },
        spa: { official: "República Argentina", common: "Argentina" },
      },
    },
    tld: [".ar"],
    cca2: "AR",
    ccn3: "032",
    cca3: "ARG",
    cioc: "ARG",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { ARS: { name: "Argentine peso", symbol: "$" } },
    idd: { root: "+5", suffixes: ["4"] },
    capital: "Buenos Aires",
    altSpellings: ["AR", "Argentine Republic", "República Argentina"],
    region: "Americas",
    subregion: "South America",
    languages: { grn: "Guaraní", spa: "Spanish" },
    translations: {
      ara: { official: "جمهورية الأرجنتين", common: "الأرجنتين" },
      bre: { official: "Republik Arc'hantina", common: "Arc'hantina" },
      ces: { official: "Argentinská republika", common: "Argentina" },
      cym: { official: "Gweriniaeth yr Ariannin", common: "Ariannin" },
      deu: { official: "Argentinische Republik", common: "Argentinien" },
      est: { official: "Argentina Vabariik", common: "Argentina" },
      fin: { official: "Argentiinan tasavalta", common: "Argentiina" },
      fra: { official: "République argentine", common: "Argentine" },
      hrv: { official: "Argentinski Republika", common: "Argentina" },
      hun: { official: "Argentin Köztársaság", common: "Argentína" },
      ita: { official: "Repubblica Argentina", common: "Argentina" },
      jpn: { official: "アルゼンチン共和国", common: "アルゼンチン" },
      kor: { official: "아르헨티나 공화국", common: "아르헨티나" },
      nld: { official: "Argentijnse Republiek", common: "Argentinië" },
      per: { official: "جمهوری آرژانتین", common: "آرژانتین" },
      pol: { official: "Republika Argentyńska", common: "Argentyna" },
      por: { official: "República Argentina", common: "Argentina" },
      rus: { official: "Аргентинская Республика", common: "Аргентина" },
      slk: { official: "Argentínska republika", common: "Argentína" },
      spa: { official: "República Argentina", common: "Argentina" },
      srp: { official: "Аргентинска Република", common: "Аргентина" },
      swe: { official: "Republiken Argentina", common: "Argentina" },
      tur: { official: "Arjantin Cumhuriyeti", common: "Arjantin" },
      urd: { official: "جمہوریہ ارجنٹائن", common: "ارجنٹائن" },
      zho: { official: "阿根廷共和国", common: "阿根廷" },
    },
    latlng: [-34.0, -64.0],
    landlocked: false,
    borders: ["BOL", "BRA", "CHL", "PRY", "URY"],
    area: 2780400.0,
    demonyms: {
      eng: { f: "Argentine", m: "Argentine" },
      fra: { f: "Argentine", m: "Argentin" },
    },
    flag: "\uD83C\uDDE6\uD83C\uDDF7",
    maps: {
      googleMaps: "https://goo.gl/maps/Z9DXNxhf2o93kvyc6",
      openStreetMaps: "https://www.openstreetmap.org/relation/286393",
    },
    population: 45376763,
    gini: { 2019: 42.9 },
    fifa: "ARG",
    car: { signs: ["RA"], side: "right" },
    timezones: ["UTC-03:00"],
    continents: ["South America"],
    flags: {
      png: "https://flagcdn.com/w320/ar.png",
      svg: "https://flagcdn.com/ar.svg",
      alt: "The flag of Argentina features three equal horizontal bands of light blue, white and light blue. A brown-edged golden sun is centered in the white band.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/ar.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/ar.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [-34.58, -58.67] },
    postalCode: { format: "@####@@@", regex: "^([A-Z]\\d{4}[A-Z]{3})$" },
  },
  {
    name: {
      common: "Spain",
      official: "Kingdom of Spain",
      nativeName: {
        spa: { official: "Reino de España", common: "España" },
      },
    },
    tld: [".es"],
    cca2: "ES",
    ccn3: "724",
    cca3: "ESP",
    cioc: "ESP",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    idd: { root: "+3", suffixes: ["4"] },
    capital: "Madrid",
    altSpellings: ["ES", "Kingdom of Spain", "Reino de España"],
    region: "Europe",
    subregion: "Southern Europe",
    languages: { spa: "Spanish" },
    translations: {
      ara: { official: "مملكة إسبانيا", common: "إسبانيا" },
      bre: { official: "Rouantelezh Spagn", common: "Spagn" },
      ces: { official: "Španělské království", common: "Španělsko" },
      cym: { official: "Kingdom of Spain", common: "Spain" },
      deu: { official: "Königreich Spanien", common: "Spanien" },
      est: { official: "Hispaania Kuningriik", common: "Hispaania" },
      fin: { official: "Espanjan kuningaskunta", common: "Espanja" },
      fra: { official: "Royaume d'Espagne", common: "Espagne" },
      hrv: { official: "Kraljevina Španjolska", common: "Španjolska" },
      hun: { official: "Spanyol Királyság", common: "Spanyolország" },
      ita: { official: "Regno di Spagna", common: "Spagna" },
      jpn: { official: "スペイン王国", common: "スペイン" },
      kor: { official: "에스파냐 왕국", common: "스페인" },
      nld: { official: "Koninkrijk Spanje", common: "Spanje" },
      per: { official: "پادشاهی اسپانیا", common: "اسپانیا" },
      pol: { official: "Królestwo Hiszpanii ", common: "Hiszpania" },
      por: { official: "Reino de Espanha", common: "Espanha" },
      rus: { official: "Королевство Испания", common: "Испания" },
      slk: { official: "Španielske kráľovstvo", common: "Španielsko" },
      spa: { official: "Reino de España", common: "España" },
      srp: { official: "Краљевина Шпанија", common: "Шпанија" },
      swe: { official: "Konungariket Spanien", common: "Spanien" },
      tur: { official: "İspanya Krallığı", common: "İspanya" },
      urd: { official: "مملکتِ ہسپانیہ", common: "ہسپانیہ" },
      zho: { official: "西班牙王国", common: "西班牙" },
    },
    latlng: [40.0, -4.0],
    landlocked: false,
    borders: ["AND", "FRA", "GIB", "PRT", "MAR"],
    area: 505992.0,
    demonyms: {
      eng: { f: "Spanish", m: "Spanish" },
      fra: { f: "Espagnole", m: "Espagnol" },
    },
    flag: "\uD83C\uDDEA\uD83C\uDDF8",
    maps: {
      googleMaps: "https://goo.gl/maps/138JaXW8EZzRVitY9",
      openStreetMaps: "https://www.openstreetmap.org/relation/1311341",
    },
    population: 10000,
    gini: { 2018: 34.7 },
    fifa: "ESP",
    car: { signs: ["E"], side: "right" },
    timezones: ["UTC", "UTC+01:00"],
    continents: ["Europe"],
    flags: {
      png: "https://flagcdn.com/w320/es.png",
      svg: "https://flagcdn.com/es.svg",
      alt: "The flag of Spain.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/es.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/es.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [40.4, -3.68] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
  },
];
